repos:
  - repo: local
    hooks:
      - id: sync-library
        name: Sync bookinfo_lib to all charms
        entry: ./scripts/sync-library.sh
        language: script
        pass_filenames: false
        always_run: true
        files: ^charms/bookinfo-libs-k8s/lib/charms/bookinfo_lib/